version: '3.8'

services:
  # Backend Django service
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: always
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
      - ./db.sqlite3:/app/db.sqlite3
    env_file:
      - .env
    depends_on:
      - setup-app
    networks:
      - app-network

  # Setup service for database initialization
  setup-app:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: sh -c "python manage.py migrate && python manage.py collectstatic --noinput && python setup.py --auto-setup"
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
      - ./db.sqlite3:/app/db.sqlite3
    env_file:
      - .env
    networks:
      - app-network

  # Frontend React build and deploy
  frontend-build:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - frontend-build:/app/build
      - ./frontend/static/frontend/react:/app/deploy
    command: sh -c "npm run deploy"
    networks:
      - app-network

  # Nginx service for serving the application
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    volumes:
      - ./staticfiles:/var/www/static
      - ./media:/var/www/media
    depends_on:
      - backend
      - frontend-build
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  frontend-build: