version: '3.8'

services:
  # Backend Django service
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: always
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
      - ./db.sqlite3:/app/db.sqlite3
    env_file:
      - .env
    networks:
      - app-network

  # Frontend React build
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./staticfiles:/app/static
    networks:
      - app-network

  # Nginx service for serving the application
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    volumes:
      - ./staticfiles:/var/www/static
      - ./media:/var/www/media
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge