# Generated by Django 5.1.7 on 2025-03-14 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulegeneration',
            name='base_prompt_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rulegeneration',
            name='prompt_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
