# Generated by Django 5.1.7 on 2025-04-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_appsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="rulegeneration",
            name="error",
            field=models.TextField(blank=True, null=True),
        ),
    ]
