# Generated by Django 5.1.7 on 2025-03-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_prompttemplate_rulegeneration_prompt_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulegeneration',
            name='workspace_name',
            field=models.CharField(default='Unnamed Workspace', max_length=255),
        ),
    ]
